version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      time: "15:00"
      timezone: "Europe/Berlin"
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    groups:
      go-modules:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      time: "15:00"
      timezone: "Europe/Berlin"
      interval: "daily"
    groups:
      action-deps:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /examples/simple
    allow:
      - dependency-type: "direct"
    schedule:
      time: "15:00"
      timezone: "Europe/Berlin"
      interval: "weekly"
