version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      time: "15:00"
      timezone: "Europe/Berlin"
      interval: "weekly"
    groups:
      go-modules:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /examples/simple
    schedule:
      interval: daily
